### ISSUE TITLE
Report ritiri

### ISSUE THREAD

**Issue by mognons** [mognons/ReteTalenti#11]
Il report NON riporta i dati necessari per l'incrocio con le eccedenze, mancando difatti l'ID_ECCEDENZA che consente tale legame.

<img width="1169" alt="bug_report" src="https://cloud.githubusercontent.com/assets/1758698/11456778/622aae08-9694-11e5-82fc-71e15b122333.png">

**Comment by gminardi** [comment]
In realtà la colonna "id prodotto" nell'excel è l'ID_ECCEDENZA.... se non sbaglio.

**Comment by mognons** [comment]
Non sbagli, ma è comunque sbagliato visto che quella colonna non è l'id prodotto (nemmeno esiste il concetto). 

Dicitura corretta, insieme ad altre banalità. 

A domani, dopo la pull mattutina :)


Alberto Mognoni


MILANO - ITALY
e-mail: 	alberto.mognoni@gmail.com
mobile: 	+39-338.7923.715
