### ISSUE TITLE
Data scadenza eccedenza su messaggio da sistema

### ISSUE THREAD

**Issue by gminardi** [mognons/ReteTalenti#12]
I messaggi (comprensibilmente) non sono "dinamici"...
1. inserisco una nuova eccedenza con scadenza X
2. vado in edit e modifico per esempio la scadenza
3. mi loggo con altra utenza e vedo il messaggio da sistema: riporta la segnalazione della nuova eccedenza ma con dati non aggiornati
![screenshot_1](https://cloud.githubusercontent.com/assets/10599438/11469455/b3b9a716-9756-11e5-94c2-06d2304aad88.png)

**Comment by mognons** [comment]
Ci sto pensando su, forse qualcosa si può fare o si può predisporre per una versione 1.1
