### ISSUE TITLE
Messaggio di errore ambiguo in modifica ritiro

### ISSUE THREAD

**Issue by gminardi** [mognons/ReteTalenti#14]
Nel modifcare una prenotazione RITIRO appena inserita appare il messaggio "errore di comunicazione con il server". 
![screenshot_2](https://cloud.githubusercontent.com/assets/10599438/11469954/4a7494ba-975a-11e5-8aad-1b78ebd4eabe.png)

**Comment by mognons** [comment]
Trattasi di svista del programmatore (ehm...), corretta e funzionante.
