### ISSUE TITLE
Gestione ritiri scaduti 

### ISSUE THREAD

**Issue by gminardi** [mognons/ReteTalenti#16]
I ritiri scaduti attualmente si accumulano
![screenshot_4](https://cloud.githubusercontent.com/assets/10599438/11470400/94cd676e-975d-11e5-92e6-b6bb0cd5dcf7.png)

**Comment by mognons** [comment]
Prevediamo una funzione di "ripulitura" per il SYSADM?

**Comment by mognons** [comment]
In aggiunta possiamo mettere un filtro alla select nel DAO per cui non vediamo i ritiri scaduti da una settimana (o 3 giorni)
