### ISSUE TITLE
gestione segnalazione eccedenze

### ISSUE THREAD

**Issue by raouldigi** [mognons/ReteTalenti#7]
comapre  form validation dopo l'inserimento della data nel campo  scandenza

**Comment by mognons** [comment]
Working on it....

**Comment by mognons** [comment]
Risolto: nei campi che usano un datepicker occorre aggiungere "datepicker" all'interno dell'attributo class del campo, es: class="validate[required, custom[date]] **datepicker**". Ho corretto anche le diciture in italiano che riportavano il senso contrario (antecedente al posto di successiva e viceversa)
